export const backgrounds = [
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-violet-200 from-5% via-indigo-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-red-400 from-5% via-blue-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-red-400 from-5% via-lime-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-amber-400 from-5% via-cyan-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-emerald-400 from-10% via-lime-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-cyan-400 from-15% via-emerald-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-400 from-15% via-fuchsia-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-stone-400 from-15% via-teal-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-fuchsia-400 from-10% via-blue-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-400 from-5% via-stone-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-amber-400 from-15% via-purple-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-red-400 from-10% via-lime-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-cyan-200 from-5% via-emerald-800  via-50%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-200 from-5% via-red-800  via-30%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-pink-300 from-15% via-teal-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-fuchsia-300 from-5% via-red-800  via-40%  to-black to-80%',
   'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-yellow-300 from-5% via-teal-800  via-50%  to-black to-80%',
] 