export const sounds = [
    {
      author: '50 Cent, Olivia',
      title: '50 Cent, Olivia – Candy Shop',
      src: '/audio/50 Cent, Olivia – Candy Shop.mp3',
      id: 1,
      img: '/img/50 Cent, Olivia – Candy Shop.jpg',
      favorite: false,
    },
    {
      author: 'Akon, Eminem',
      title: 'Akon, Eminem – Smack That',
      src: '/audio/Akon, Eminem – Smack That.mp3',
      id: 2,
      img: '/img/Akon, Eminem – Smack That.jpg',
      favorite: false,
    },
    {
      author: 'Alan Walker',
      title: 'Alan Walker – Faded',
      src: '/audio/Alan Walker – Faded.mp3',
      id: 3,
      img: '/img/Alan Walker – Faded.png',
      favorite: false,
    },
    {
      author: 'Alec Benjamin',
      title: 'Alec Benjamin – Let Me Down Slowly',
      src: '/audio/Alec Benjamin – Let Me Down Slowly.mp3',
      id: 4,
      img: '/img/Alec Benjamin – Let Me Down Slowly.jpg',
      favorite: false,
    },
    {
      author: 'Ed Sheeran',
      title: 'Ed Sheeran – Shape of You',
      src: '/audio/Ed Sheeran – Shape of You.mp3',
      id: 5,
      img: '/img/Ed Sheeran – Shape of You.jpg',
      favorite: false,
    },
    {
      author: 'Eminem',
      title: 'Eminem – Mockingbird',
      src: '/audio/Eminem – Mockingbird.mp3',
      id: 6,
      img: '/img/Eminem – Mockingbird.jpg',
      favorite: false,
    },
    {
      author: 'Eminem',
      title: 'Eminem – Not Afraid',
      src: '/audio/Eminem – Not Afraid.mp3',
      id: 7,
      img: '/img/Eminem – Not Afraid.jpg',
      favorite: false,
    },
    {
      author: 'Eminem, Rihanna',
      title: 'Eminem, Rihanna – Love The Way You Lie',
      src: '/audio/Eminem, Rihanna – Love The Way You Lie.mp3',
      id: 8,
      img: '/img/Eminem, Rihanna – Love The Way You Lie.jpg',
      favorite: false,
    },
    {
      author: 'Enrique Iglesias',
      title: 'Enrique Iglesias – Ring My Bells',
      src: '/audio/Enrique Iglesias – Ring My Bells.mp3',
      id: 9,
      img: '/img/Enrique Iglesias – Ring My Bells.png',
      favorite: false,
    },
    {
      author: 'Europe',
      title: 'Europe – The Final Countdown',
      src: '/audio/Europe – The Final Countdown.mp3',
      id: 10,
      img: '/img/Europe – The Final Countdown.jpg',
      favorite: false,
    },
    {
      author: 'Evanescence',
      title: 'Evanescence – Bring Me To Life',
      src: '/audio/Evanescence – Bring Me To Life.mp3',
      id: 11,
      img: '/img/Evanescence – Bring Me To Life.jpg',
      favorite: false,
    },
    {
      author: 'Inna',
      title: 'Inna – Hot',
      src: '/audio/Inna – Hot.mp3',
      id: 12,
      img: '/img/Inna – Hot.jpg',
      favorite: false,
    },
    {
      author: 'Nelly Furtado',
      title: 'Nelly Furtado – Say It Right',
      src: '/audio/Nelly Furtado – Say It Right.mp3',
      id: 13,
      img: '/img/Nelly Furtado – Say It Right.webp',
      favorite: false,
    },
    {
      author: 'Rammstein',
      title: 'Rammstein – DU HAST',
      src: '/audio/Rammstein – DU HAST.mp3',
      id: 14,
      img: '/img/Rammstein – DU HAST.jpg',
      favorite: false,
    },
    {
      author: 'Rihanna',
      title: 'Rihanna – Diamonds',
      src: '/audio/Rihanna – Diamonds.mp3',
      id: 15,
      img: '/img/Rihanna – Diamonds.jpg',
      favorite: false,
    },
    {
      author: 'The Black Eyed Peas',
      title: 'The Black Eyed Peas – My Humps',
      src: '/audio/The Black Eyed Peas – My Humps.mp3',
      id: 16,
      img: '/img/The Black Eyed Peas – My Humps.jpg',
      favorite: false,
    },
    {
      author: 'Usher, Lil Jon, Ludacris',
      title: 'Usher, Lil Jon, Ludacris – Yeah!',
      src: '/audio/Usher, Lil Jon, Ludacris – Yeah!.mp3',
      id: 17,
      img: '/img/Usher, Lil Jon, Ludacris – Yeah!.webp',
      favorite: false,
    },
  ]


